FROM alpine

RUN 2

RUN 3

RUN 4

RUN 5

RUN 6

RUN 7

RUN 8

RUN 9

######################################
# NEXT RELEASE CHANGES START THRESHOLD
# info1
# info2
# info3
# info4
#####################################

RUN 10

ARG 11

ARG 12

####################################
# NEXT RELEASE CHANGES END THRESHOLD
# info1
# info2
# info3
####################################